import assert from "node:assert/strict";
import { randomUUID, createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { test } from "node:test";
import { loadMigrations, runMigrations, type Migration } from "../src/migrations.ts";
import { createPostgresDatabase, getSharedPostgresControlTowerRepository, closeSharedPostgresDatabase } from "../src/postgres.ts";
import { ControlTowerRepository } from "../src/repository.ts";
import type { TransactionalDatabase } from "../src/types.ts";
import { mkdtemp, mkdir, writeFile, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ProcessingJobRepository } from '../src/processing-jobs.ts';
import { processSourceJob } from '../../knowledge/src/process-job.ts';
import { MarkdownVault, digest } from '../../knowledge/src/markdown-vault.ts';
import { providedDraft, sourceRequest } from '../../knowledge/src/source-article.ts';
import { OpenAIArticleGenerator } from '../../knowledge/src/openai-article.ts';
import type { ArticleGenerator, SourceInput } from '../../knowledge/src/article-types.ts';

const exec = promisify(execFile);
const connection = process.env.TEST_DATABASE_URL;
if (!connection) throw new Error("Set TEST_DATABASE_URL to a local, disposable business_os_test database (CREATEDB role). Never use DATABASE_URL for this test.");
const endpoint = new URL(connection);
if (!["postgres:", "postgresql:"].includes(endpoint.protocol) ||
    !["localhost", "127.0.0.1", "[::1]"].includes(endpoint.hostname) ||
    endpoint.pathname !== "/business_os_test" ||
    [...endpoint.searchParams.keys()].some((key) => key !== "host") ||
    endpoint.searchParams.getAll("host").length > 1 ||
    (endpoint.searchParams.has("host") && !endpoint.searchParams.get("host")?.startsWith("/"))) {
  throw new Error("Integration tests require a local business_os_test database; only an optional absolute Unix-socket host is accepted");
}
const migrations = await loadMigrations();

async function fixture(operation: (db: TransactionalDatabase, url: string) => Promise<void>) {
  const admin = createPostgresDatabase(endpoint.href);
  const name = `business_os_test_${randomUUID().replaceAll("-", "")}`;
  let created = false;
  let db: TransactionalDatabase | undefined;
  try {
    await admin.query(`CREATE DATABASE "${name}" TEMPLATE template0`);
    created = true;
    const url = new URL(endpoint);
    url.pathname = `/${name}`;
    db = createPostgresDatabase(url.href);
    await operation(db, url.href);
  } finally {
    await closeSharedPostgresDatabase();
    await db?.close();
    try {
      // Only the database generated by this fixture can be dropped; never the supplied DB.
      if (created) await admin.query(`DROP DATABASE "${name}" WITH (FORCE)`);
    } finally { await admin.close(); }
  }
}

function migration(version: string, sql: string): Migration {
  return { version, sql, checksum: createHash("sha256").update(sql).digest("hex") };
}

const source: SourceInput = { title: 'Synthetic input', body: '12 examples in 30 minutes.\n', sourceType: 'document' };
async function vaultFixture(operation: (vault: MarkdownVault, root: string) => Promise<void>) {
  const root = await mkdtemp(join(tmpdir(), 'business-os-job-'));
  try {
    await mkdir(join(root, 'vault'));
    await operation(await MarkdownVault.connect(join(root, 'vault')), root);
  } finally { await rm(root, { recursive: true, force: true }); }
}

async function populate(db: TransactionalDatabase) {
  await db.query(`INSERT INTO organizations (id, name) VALUES ('org', 'Test organization');
    INSERT INTO workspaces (id, organization_id, name) VALUES ('a', 'org', 'Workspace A'), ('b', 'org', 'Workspace B');
    INSERT INTO approval_requests (id, workspace_id, action_type, summary, status, requested_by)
      VALUES ('approval-a', 'a', 'test', 'A only', 'preview', 'fixture'), ('approval-b', 'b', 'test', 'B only', 'preview', 'fixture');
    INSERT INTO operating_loop_runs (id, workspace_id, name) VALUES ('loop-a', 'a', 'A loop'), ('loop-b', 'b', 'B loop');`);
}

test("PostgreSQL migration and repository integration", { timeout: 120_000 }, async (t) => {
  await t.test("empty install, concurrent runners, repeat and checksum/version guards", () => fixture(async (db, url) => {
    const other = createPostgresDatabase(url);
    try {
      const results = await Promise.all([runMigrations(db, migrations), runMigrations(other, migrations)]);
      assert.deepEqual(results.map((r) => r.length).sort(), [0, migrations.length]);
      assert.deepEqual(await runMigrations(db, migrations), []);
      const history = await db.query("SELECT version FROM business_os_migrations ORDER BY version");
      assert.deepEqual(history.rows.map((r) => r.version), migrations.map((m) => m.version));
      await assert.rejects(runMigrations(db, [{ ...migrations[0], checksum: "0".repeat(64) }, ...migrations.slice(1)]), /history mismatch/);
      await assert.rejects(runMigrations(db, migrations.slice(0, 1)), /history mismatch/);
      await assert.rejects(runMigrations(db, [...migrations].reverse()), /ordered/);
      await assert.rejects(runMigrations(db, [migrations[0], migrations[0]]), /ordered/);
    } finally { await other.close(); }
  }));

  await t.test("failed first install rolls back schema and ledger", () => fixture(async (db) => {
    await assert.rejects(runMigrations(db, [...migrations, migration("999_failure.sql", "CREATE TABLE rollback_probe (id int); SELECT missing_column FROM rollback_probe;")]));
    const tables = await db.query("SELECT tablename FROM pg_tables WHERE schemaname = 'public'");
    assert.equal(tables.rows.length, 0);
    assert.equal((await runMigrations(db, migrations)).length, migrations.length);
  }));

  await t.test("failed upgrade preserves earlier schema and history", () => fixture(async (db) => {
    await runMigrations(db, migrations);
    await populate(db);
    await assert.rejects(runMigrations(db, [...migrations, migration("999_failure.sql", "ALTER TABLE tasks ADD COLUMN rollback_probe text; SELECT 1 / 0;")]));
    assert.equal((await db.query("SELECT version FROM business_os_migrations")).rows.length, migrations.length);
    assert.equal((await db.query("SELECT column_name FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'rollback_probe'")).rows.length, 0);
    assert.equal((await db.query("SELECT id FROM workspaces")).rows.length, 2);
  }));

  await t.test("legacy schema is refused without changing existing data", () => fixture(async (db) => {
    await db.query("CREATE TABLE legacy_data (value text); INSERT INTO legacy_data VALUES ('keep');");
    await assert.rejects(runMigrations(db, migrations), /Untracked public schema/);
    assert.equal((await db.query("SELECT value FROM legacy_data")).rows[0].value, "keep");
    assert.equal((await db.query("SELECT to_regclass('public.business_os_migrations') AS ledger")).rows[0].ledger, null);
  }));

  await t.test('job migration upgrades the recorded baseline without changing workspace data', () => fixture(async db => {
    await runMigrations(db, migrations.slice(0, 2)); await populate(db);
    assert.deepEqual(await runMigrations(db, migrations), ['004_processing_jobs.sql']);
    assert.deepEqual((await db.query('SELECT id FROM workspaces ORDER BY id')).rows, [{ id: 'a' }, { id: 'b' }]);
    assert.equal((await db.query('SELECT id FROM approval_requests')).rows.length, 2);
    assert.deepEqual(await runMigrations(db, migrations), []);
  }));

  await t.test("workspace references reject cross-workspace source links and preserve owner on source deletion", () => fixture(async (db) => {
    await runMigrations(db, migrations);
    await populate(db);
    await assert.rejects(db.query("INSERT INTO learning_items (id, workspace_id, title, destination, source_run_id) VALUES ('bad', 'a', 'Bad link', 'wiki', 'loop-b')"), { code: "23503" });
    await db.query("INSERT INTO learning_items (id, workspace_id, title, destination, source_run_id) VALUES ('good', 'a', 'Good link', 'wiki', 'loop-a')");
    await db.query("DELETE FROM operating_loop_runs WHERE id = 'loop-a'");
    assert.deepEqual((await db.query("SELECT workspace_id, source_run_id FROM learning_items")).rows, [{ workspace_id: "a", source_run_id: null }]);
  }));

  await t.test("invalid legacy links make the additive migration roll back", () => fixture(async (db) => {
    await runMigrations(db, migrations.slice(0, 1));
    await populate(db);
    await db.query("INSERT INTO learning_items (id, workspace_id, title, destination, source_run_id) VALUES ('bad', 'a', 'Old bad link', 'wiki', 'loop-b')");
    await assert.rejects(runMigrations(db, migrations), { code: "23503" });
    assert.equal((await db.query("SELECT version FROM business_os_migrations")).rows.length, 1);
    assert.equal((await db.query("SELECT source_run_id FROM learning_items")).rows[0].source_run_id, "loop-b");
    assert.equal((await db.query("SELECT 1 FROM pg_constraint WHERE conname = 'learning_items_source_run_id_fkey'")).rows.length, 1);
  }));

  await t.test("repository reads and writes stay within the requested workspace", () => fixture(async (db) => {
    await runMigrations(db, migrations);
    await populate(db);
    const repository = new ControlTowerRepository(db);
    const snapshot = await repository.getDashboardSnapshot("a");
    assert.equal(snapshot.dataSource, "postgres");
    assert.equal(snapshot.identity.workspaceName, "Workspace A");
    assert.deepEqual(snapshot.approvals.map((a) => a.id), ["approval-a"]);
    assert.deepEqual(snapshot.loops.map((a) => a.id), ["loop-a"]);
    await assert.rejects(repository.reviewApproval({ workspaceId: "a", approvalId: "approval-b", decision: "approved", actorId: "tester" }), /missing/);
    assert.equal((await db.query("SELECT status FROM approval_requests WHERE id = 'approval-b'")).rows[0].status, "preview");
    assert.equal((await db.query("SELECT id FROM approval_events")).rows.length, 0);
  }));

  await t.test("concurrent approval permits one transition and one audit record", () => fixture(async (db) => {
    await runMigrations(db, migrations);
    await populate(db);
    const repository = new ControlTowerRepository(db);
    const result = await Promise.allSettled(["approved", "rejected"].map((decision) => repository.reviewApproval({
      workspaceId: "a", approvalId: "approval-a", decision: decision as "approved" | "rejected", actorId: "tester",
    })));
    assert.equal(result.filter((r) => r.status === "fulfilled").length, 1);
    assert.equal((await db.query("SELECT id FROM approval_events")).rows.length, 1);
    assert.equal((await db.query("SELECT id FROM activity_events")).rows.length, 1);
  }));

  await t.test("audit insertion failure rolls back approval and earlier event", () => fixture(async (db) => {
    await runMigrations(db, migrations);
    await populate(db);
    await db.query("ALTER TABLE activity_events ADD CONSTRAINT fail_fixture CHECK (event_type <> 'approval_reviewed')");
    const repository = new ControlTowerRepository(db);
    await assert.rejects(repository.reviewApproval({ workspaceId: "a", approvalId: "approval-a", decision: "approved", actorId: "tester" }), { code: "23514" });
    assert.equal((await db.query("SELECT status FROM approval_requests WHERE id = 'approval-a'")).rows[0].status, "preview");
    assert.equal((await db.query("SELECT id FROM approval_events")).rows.length, 0);
    // The connection is usable after rollback.
    await db.query("ALTER TABLE activity_events DROP CONSTRAINT fail_fixture");
    await repository.reviewApproval({ workspaceId: "a", approvalId: "approval-a", decision: "approved", actorId: "tester" });
  }));

  await t.test("web runtime reuses its pool and committed data survives a new process", () => fixture(async (db, url) => {
    await runMigrations(db, migrations);
    await populate(db);
    const first = getSharedPostgresControlTowerRepository(url);
    const second = getSharedPostgresControlTowerRepository(url);
    assert.equal(first.database, second.database);
    const pid = async (database: TransactionalDatabase) => (await database.query("SELECT pg_backend_pid() AS pid")).rows[0].pid;
    assert.equal(await pid(first.database), await pid(second.database));
    assert.throws(() => getSharedPostgresControlTowerRepository(`${url}changed`), /restart/);
    await first.repository.reviewApproval({ workspaceId: "a", approvalId: "approval-a", decision: "approved", actorId: "tester" });
    await closeSharedPostgresDatabase();
    const { stdout } = await exec(process.execPath, ["--input-type=module", "-e", `
      import { createPostgresDatabase } from ${JSON.stringify(new URL("../src/postgres.ts", import.meta.url).href)};
      const db = createPostgresDatabase(process.env.TEST_DATABASE_URL);
      try { console.log(JSON.stringify((await db.query("SELECT status FROM approval_requests WHERE id = 'approval-a'")).rows)); }
      finally { await db.close(); }
    `], { env: { ...process.env, TEST_DATABASE_URL: url }, timeout: 15_000 });
    assert.deepEqual(JSON.parse(stdout), [{ status: "approved" }]);
  }));

  await t.test("Control Tower server adapter loads and reviews the configured workspace", () => fixture(async (db, url) => {
    await runMigrations(db, migrations);
    await populate(db);
    const { stdout } = await exec(process.execPath, ["--input-type=module", "-e", `
      import { loadDashboard, reviewApproval } from ${JSON.stringify(new URL("../../../apps/control-tower/lib/dashboard.ts", import.meta.url).href)};
      import { closeSharedPostgresDatabase } from ${JSON.stringify(new URL("../src/postgres.ts", import.meta.url).href)};
      try {
        const before = await loadDashboard();
        await reviewApproval({ approvalId: "approval-a", decision: "approved" });
        const after = await loadDashboard();
        console.log(JSON.stringify({ source: before.dataSource, name: before.identity.workspaceName, before: before.approvals.length, after: after.approvals.length }));
      } finally { await closeSharedPostgresDatabase(); }
    `], { env: { ...process.env, DATABASE_URL: url, BUSINESS_OS_WORKSPACE_ID: "a", BUSINESS_OS_OPERATOR_ID: "fixture-owner" }, timeout: 15_000 });
    assert.deepEqual(JSON.parse(stdout), { source: "postgres", name: "Workspace A", before: 1, after: 0 });
    assert.equal((await db.query("SELECT status FROM approval_requests WHERE id = 'approval-b'")).rows[0].status, "preview");
  }));
});

test('Durable processing jobs', { timeout: 120_000 }, async t => {
  await t.test('concurrent request/claim, workspace foreign keys and stale-attempt rejection', () => fixture(async db => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db);
    const request = { workspaceId: 'a', vaultId: digest('vault'), requestHash: digest('request'), maxAttempts: 3 };
    const [a, b] = await Promise.all([jobs.request(request), jobs.request(request)]);
    assert.equal(a.id, b.id);
    assert.equal((await jobs.inspect('a', a.id))!.events.length, 1);
    assert.equal(await jobs.get('b', a.id), null);
    assert.equal(await jobs.cancel('b', a.id), null);
    assert.equal(await jobs.claim('b', a.id, false), null);
    const other = await jobs.request({ ...request, workspaceId: 'b' });
    assert.notEqual(a.id, other.id);
    assert.deepEqual((await jobs.list('b')).map(j => j.id), [other.id]);
    const claims = await Promise.all([jobs.claim('a', a.id, false), jobs.claim('a', a.id, false)]);
    assert.equal(claims.filter(Boolean).length, 1);
    const claim = claims.find(Boolean)!;
    await assert.rejects(jobs.finish('a', a.id, 'wrong-attempt', { status: 'succeeded' }), /attempt-not-running/);
    await assert.rejects(db.query("INSERT INTO processing_events (workspace_id,job_id,attempt_id,event_type) VALUES ('b',$1,$2,'bad')", [other.id, claim.attemptId]), { code: '23503' });
    await assert.rejects(db.query("INSERT INTO processing_model_calls (workspace_id,job_id,attempt_id,sequence,model,status) VALUES ('b',$1,$2,1,'fixture','started')", [other.id, claim.attemptId]), { code: '23503' });
    await db.query("ALTER TABLE processing_events ADD CONSTRAINT fail_job_event CHECK (event_type <> 'succeeded')");
    await assert.rejects(jobs.finish('a', a.id, claim.attemptId, { status: 'succeeded' }), { code: '23514' });
    assert.equal((await jobs.get('a', a.id))!.status, 'running');
    assert.equal((await jobs.inspect('a', a.id))!.attempts[0].status, 'running');
  }));

  await t.test('provided draft persists one job; input/policy/vault changes create separate requests', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db), generator = providedDraft('12 examples, 30 minutes.');
    let calls = 0; const generate = generator.generate;
    generator.generate = async (...args) => { calls++; return generate(...args); };
    const options = { jobs, generator, vault, workspaceId: 'a' };
    const first = await processSourceJob(source, options);
    assert.equal(first.status, 'succeeded'); assert.equal(first.result?.status, 'created');
    const duplicate = await processSourceJob({ ...source, title: 'Different display title' }, options);
    assert.equal(duplicate.id, first.id); assert.equal(calls, 1);
    const detail = (await jobs.inspect('a', first.id))!;
    assert.equal(detail.attempts.length, 1); assert.equal(detail.calls.length, 0);
    assert.deepEqual(detail.events.map(e => e.event_type), ['queued', 'running', 'succeeded']);
    assert.notEqual((await processSourceJob({ ...source, body: source.body + 'Another example.' }, options)).id, first.id);
    assert.notEqual((await processSourceJob(source, { ...options, generator: providedDraft('Different draft policy') })).id, first.id);
    assert.notEqual((await jobs.request({ workspaceId: 'a', vaultId: digest('another-vault'), requestHash: first.requestHash, maxAttempts: 3 })).id, first.id);
  })));

  await t.test('explicit retries stop at the original limit and redact unexpected errors', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db); let calls = 0;
    const generator: ArticleGenerator = { fingerprint: 'fails', async generate() { calls++; throw new Error('private body and credential must not persist'); } };
    const options = { jobs, generator, vault, workspaceId: 'a', maxAttempts: 2 };
    const first = await processSourceJob(source, options);
    assert.equal(first.status, 'failed'); assert.equal(first.reason, 'processing-failed');
    assert.equal((await processSourceJob(source, options)).attemptCount, 1);
    const retry = await processSourceJob(source, { ...options, retry: true });
    assert.equal(retry.attemptCount, 2);
    const exhausted = await processSourceJob(source, { ...options, retry: true, maxAttempts: 5 });
    assert.equal(exhausted.attemptCount, 2); assert.equal(exhausted.maxAttempts, 2); assert.equal(calls, 2);
    assert.equal(JSON.stringify(await jobs.inspect('a', first.id)).includes('private body'), false);
  })));

  await t.test('queued cancellation and needs-input never invoke generation', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db);
    const generator: ArticleGenerator = { fingerprint: 'never-call', async generate() { assert.fail('must not generate'); } };
    const queued = await jobs.request({ workspaceId: 'a', vaultId: digest(vault.root), requestHash: sourceRequest(source, generator.fingerprint).requestHash, maxAttempts: 3 });
    assert.equal((await jobs.cancel('a', queued.id))!.status, 'cancelled');
    assert.equal((await processSourceJob(source, { jobs, generator, vault, workspaceId: 'a', retry: true })).attemptCount, 0);
    const needsInput = await processSourceJob({ ...source, body: 'https://example.com' }, { jobs, generator, vault, workspaceId: 'a' });
    assert.equal(needsInput.status, 'needs-input'); assert.equal(needsInput.reason, 'source-body-required');
    assert.deepEqual(await readdir(vault.root), []);
  })));

  await t.test('explicit retry can succeed while reusing the preserved Raw', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db); let calls = 0;
    const generator: ArticleGenerator = { fingerprint: 'retry-success', async generate() {
      if (++calls === 1) throw new Error('temporary fixture failure');
      return { body: 'Synthetic result after retry.', mode: 'provided-draft' };
    } };
    const options = { jobs, generator, vault, workspaceId: 'a' };
    const first = await processSourceJob(source, options);
    const rawFiles = await readdir(join(vault.root, '20_raw/document'));
    const second = await processSourceJob(source, { ...options, retry: true });
    assert.equal(first.id, second.id); assert.equal(second.status, 'succeeded'); assert.equal(second.attemptCount, 2);
    assert.deepEqual(await readdir(join(vault.root, '20_raw/document')), rawFiles);
    assert.deepEqual((await jobs.inspect('a', first.id))!.attempts.map(a => a.status), ['failed', 'succeeded']);
  })));

  await t.test('successful model usage is durable and repeats do not bill again', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db); let calls = 0;
    const generator = new OpenAIArticleGenerator({ apiKey: 'synthetic-test-only', fetch: async () => {
      calls++;
      return Response.json({ status: 'completed', usage: { input_tokens: 12, output_tokens: 5 },
        output: [{ type: 'message', content: [{ type: 'output_text', text: 'Synthetic completed article.' }] }] });
    } });
    const options = { jobs, generator, vault, workspaceId: 'a' };
    const result = await processSourceJob(source, options);
    assert.equal(result.status, 'succeeded');
    assert.deepEqual(result.result?.status === 'created' ? result.result.usage : null, { inputTokens: 12, outputTokens: 5, calls: 1 });
    await processSourceJob(source, options); assert.equal(calls, 1);
    assert.equal((await jobs.inspect('a', result.id))!.calls[0].status, 'reported');
  })));

  await t.test('malformed response with unknown usage is review-only, never a free retry', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db); let calls = 0;
    const generator = new OpenAIArticleGenerator({ apiKey: 'synthetic-test-only', fetch: async () => { calls++; return Response.json(null); } });
    const options = { jobs, generator, vault, workspaceId: 'a' };
    const result = await processSourceJob(source, options);
    assert.equal(result.status, 'needs-review');
    assert.equal((await jobs.inspect('a', result.id))!.calls[0].input_tokens, null);
    await processSourceJob(source, { ...options, retry: true }); assert.equal(calls, 1);
  })));

  await t.test('running cancellation is observed by the active process, preserving Raw only', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db);
    let entered!: () => void; const started = new Promise<void>(resolve => { entered = resolve; });
    const generator: ArticleGenerator = { fingerprint: 'cancel-running', async generate(_source, signal) {
      entered();
      await new Promise<void>((_resolve, reject) => {
        signal!.throwIfAborted(); signal!.addEventListener('abort', () => reject(signal!.reason), { once: true });
      });
      assert.fail('cancelled generation must not publish');
    } };
    const running = processSourceJob(source, { jobs, generator, vault, workspaceId: 'a' });
    await started;
    const id = (await db.query('SELECT id FROM processing_jobs')).rows[0].id as string;
    assert.equal((await jobs.cancel('a', id))!.status, 'running');
    assert.equal((await running).status, 'cancelled');
    assert.deepEqual(await readdir(vault.root), ['20_raw']);
    assert.equal((await jobs.inspect('a', id))!.attempts[0].status, 'cancelled');
  })));

  await t.test('partial model usage survives a later lost response; retry requires review', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db); let calls = 0;
    const generator = new OpenAIArticleGenerator({ apiKey: 'synthetic-test-only', maxChars: 100, fetch: async () => {
      if (++calls === 2) throw new Error('private upstream error');
      return Response.json({ status: 'completed', usage: { input_tokens: 10, output_tokens: 4 },
        output: [{ type: 'message', content: [{ type: 'output_text', text: 'First part.' }] }] });
    } });
    const input = { ...source, body: 'a'.repeat(80) + '\n\n' + 'b'.repeat(80) };
    const result = await processSourceJob(input, { jobs, generator, vault, workspaceId: 'a' });
    assert.equal(result.status, 'needs-review');
    const detail = (await jobs.inspect('a', result.id))!;
    assert.deepEqual(detail.calls.map(c => c.status), ['reported', 'unknown']);
    assert.equal(Number(detail.calls[0].input_tokens), 10); assert.equal(Number(detail.calls[0].output_tokens), 4);
    assert.equal(detail.calls[1].input_tokens, null); assert.equal(detail.calls[1].output_tokens, null);
    await processSourceJob(input, { jobs, generator, vault, workspaceId: 'a', retry: true });
    assert.equal(calls, 2); assert.equal(detail.attempts.length, 1);
  })));

  await t.test('usage is saved even when a received output is refused', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    const jobs = new ProcessingJobRepository(db);
    const generator = new OpenAIArticleGenerator({ apiKey: 'synthetic-test-only', fetch: async () => Response.json({
      status: 'completed', usage: { input_tokens: 7, output_tokens: 2 }, output: [{ type: 'message', content: [{ type: 'refusal' }] }],
    }) });
    const result = await processSourceJob(source, { jobs, generator, vault, workspaceId: 'a' });
    assert.equal(result.status, 'failed'); assert.equal(result.reason, 'openai-refused'); assert.equal(result.retryable, false);
    assert.equal(Number((await jobs.inspect('a', result.id))!.calls[0].input_tokens), 7);
  })));

  await t.test('DB failure before a model request prevents the call and leaves an unresolved running attempt', () => fixture(async db => vaultFixture(async vault => {
    await runMigrations(db, migrations); await populate(db);
    await db.query("ALTER TABLE processing_model_calls ADD CONSTRAINT fail_call_fixture CHECK (sequence < 0)");
    let calls = 0;
    const generator = new OpenAIArticleGenerator({ apiKey: 'synthetic-test-only', fetch: async () => { calls++; throw new Error('must not call'); } });
    const jobs = new ProcessingJobRepository(db);
    await assert.rejects(processSourceJob(source, { jobs, generator, vault, workspaceId: 'a' }), /job-store-unavailable/);
    assert.equal(calls, 0);
    const id = (await db.query('SELECT id FROM processing_jobs')).rows[0].id as string;
    assert.equal((await jobs.get('a', id))!.status, 'running');
    assert.equal(await jobs.claim('a', id, true), null);
  })));

  await t.test('new CLI processes find the same job and inspect durable history', () => fixture(async (db, url) => vaultFixture(async (vault, root) => {
    await runMigrations(db, migrations); await populate(db);
    await writeFile(join(root, 'source.md'), source.body); await writeFile(join(root, 'draft.md'), 'Synthetic supplied article.');
    const args = ['scripts/process-source.ts', '--vault', vault.root, '--source-root', root, '--source', join(root, 'source.md'),
      '--draft', join(root, 'draft.md'), '--title', source.title, '--track-job', '--workspace', 'a'];
    const env = { ...process.env, DATABASE_URL: url };
    const first = JSON.parse((await exec(process.execPath, args, { env })).stdout);
    const repeated = JSON.parse((await exec(process.execPath, args, { env })).stdout);
    assert.equal(first.status, 'succeeded'); assert.equal(repeated.id, first.id); assert.equal(repeated.attemptCount, 1);
    const inspected = JSON.parse((await exec(process.execPath, ['scripts/processing-job.ts', '--workspace', 'a', '--job', first.id], { env })).stdout);
    assert.equal(inspected.attempts.length, 1); assert.equal(inspected.events.length, 3);
    const listing = JSON.parse((await exec(process.execPath, ['scripts/processing-job.ts', '--workspace', 'a'], { env })).stdout);
    assert.deepEqual(listing.map((j: { id: string }) => j.id), [first.id]);
    await assert.rejects(exec(process.execPath, ['scripts/processing-job.ts', '--workspace', 'b', '--job', first.id], { env }));
  })));
});
